#ifndef _TIMP_TEXTURE_FORMAT_H_
#define _TIMP_TEXTURE_FORMAT_H_

namespace timp
{

enum TEXTURE_FORMAT {
	TEXTURE_INVALID = 0,
	TEXTURE_RGBA8,
	TEXTURE_RGBA4,
	TEXTURE_RGB,
	TEXTURE_RGB565,
	TEXTURE_A8,
	TEXTURE_DEPTH,	// use for render target
	TEXTURE_PVR2,
	TEXTURE_PVR4,
	TEXTURE_ETC1,
	TEXTURE_ETC2,
};

}

#endif // _TIMP_TEXTURE_FORMAT_H_